base_name: tts-model-v1
config:
  - languages:
      - hi
      - ta
      - ml
    gpu:
      count: 0
      accelerator: 'nvidia-A100'

  - languages:
      - or
      - kn
      - te
      - gu
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
