base_name: tts-model-v1
config:
  - languages:
      - hi
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "4"
    replicaCount: 5
  - languages:
      - ml
      - ta
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "5"
    replicaCount: 4
  - languages:
      - te
      - or
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "6"
    replicaCount: 4
  - languages:
      - kn
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
    replicaCount: 2
  - languages:
      - gu
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
    replicaCount: 2
