base_name: tts-model-v1
config:
  - languages:
      - hi
      - ta
      - kn
      - ml
      - gu
      - or
      - te
      - bn
    gpu:
      count: 0
      accelerator: ''
    replicaCount: 1