base_name: tts-model-v1
config:
  - languages:
      - hi
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - te
      - ml
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - gu
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - kn
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - ta
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - or
    gpu:
      count: 0
      accelerator: ''

