base_name: tts-model-v1
config:
  - languages:
      - hi
      - ta
      - ml
    gpu:
      count: 1
      accelerator: 'nvidia-A100'
    replicaCount: 1
  - languages:
      - or
      - kn
      - te
      - gu
    gpu:
      count: 1
      accelerator: 'nvidia-A100'
