base_name: tts-model-v1
config:
  - languages:
      - hi
      - ml
      - or
      - gu
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "5"
    replicaCount: 4
  - languages:
      - ta
      - te
      - kn
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "6"
    replicaCount: 4
