base_name: tts-model-v1
config:
  - languages:
      - hi
      - en
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "3"
    replicaCount: 2
    nodeName: "scn32-100g"
  - languages:
      - te
      - ml
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "3"
    replicaCount: 2
    nodeName: "scn32-100g"
  - languages:
      - gu
      - mr
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "4"
    replicaCount: 4
    nodeName: "scn32-100g"
  - languages:
      - kn
      - bn
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "5"
    replicaCount: 4
    nodeName: "scn32-100g"
  - languages:
      - ta
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "6"
    replicaCount: 4
    nodeName: "scn32-100g"
  - languages:
      - or
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "7"
    replicaCount: 4
    nodeName: "scn32-100g"

