base_name: tts-model-v1
config:
  - languages:
      - hi
      - kn
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
    replicaCount: 4
  - languages:
      - or
      - ml
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
    replicaCount: 4
  - languages:
      - gu
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "3"
    replicaCount: 4
  - languages:
      - ml
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "4"
    replicaCount: 4
  - languages:
      - ta
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "5"
    replicaCount: 4
  - languages:
      - te
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "6"
    replicaCount: 4

