apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tts-model-v1.fullname" . }}
  labels:
    {{- include "tts-model-v1.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tts-model-v1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tts-model-v1.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tts-model-v1.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Values.volumes.name }}
          hostPath:
            path: {{ .Values.volumes.path }}
            type: {{ .Values.volumes.type }}
        - name: {{ .Values.volumes.translitVolumeName }}
          hostPath:
            path: {{ .Values.volumes.translitVolumePath }}
            type: {{ .Values.volumes.translitVolumeType }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: languages
              value: {{ .Values.env.languages | squote }}
            - name: gpu
                value: {{ .Values.env.gpu | quote }}
            - name: log_level
              value: {{ .Values.env.log_level | quote }}

          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.volumes.name }}
              mountPath: {{ .Values.volumes.mountPath }}
            - name: {{ .Values.volumes.translitVolumeName }}
              mountPath: {{ .Values.volumes.translitVolumeMountPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
